const BUYER_TEMPLATE = [
  { theme: "New Lead", group: 1, activities: [
    { name: "Create new contact in CRM and add info/tags", notes: "Collect name, phone number, email, address" },
    { name: "Add neighborhood using address", notes: "" },
    { name: "Set up on at least one Automated Campaign", notes: "" },
    { name: "Add DTD2 Hashtag", notes: "Use DTD2 naming convention and their last name to create hashtag" },
    { name: "Use FB to collect info like children's names, birthdays, activities", notes: "" }
  ]},
  { theme: "Lead", group: 2, activities: [
    { name: "Prepare Buyer Presentation according to layout in 'Step by Step Guides'", notes: "Will need to draft based on answers we need from client" },
    { name: "Send all comms BEFORE presentation according to 'Step by Step Guides'", notes: "" },
    { name: "Review/Execute Exclusive Transaction Broker Agreement", notes: "Must be done before any houses have been shown" },
    { name: "Add EITHER $250 or $750 HRE broker fee", notes: "If sphere --> $250, if not --> $750. Once we hit 8,900, we are only charged $250 per transaction" },
    { name: "Create Opportunity in Bold Trail", notes: "Create opportunity, complete all contact details and upload the Exclusive Broker Agreement" },
    { name: "Create/update row in spreadsheet", notes: "Located in 'Helpful Info' file" },
    { name: "Duplicate applicable template tab and rename (Client - Buyer/Seller)", notes: "Located in 'Transaction Coordinator' file" },
    { name: "Create folders in OneDrive & Outlook (SRG Email)", notes: "" }
  ]},
  { theme: "Active Showing", group: 3, activities: [
    { name: "Establish lender", notes: "" },
    { name: "Get pre-qualification letter", notes: "" },
    { name: "Provide income/asset documentation", notes: "" },
    { name: "Create MLS subscription based on preferences", notes: "Add buyer as contact in MLS, invite to portal, set the subscription up for Daily delivery" },
    { name: "Schedule showings through ShowingTime", notes: "As properties are found, schedule showing tours in Showing Time via MLS" },
    { name: "Check Documents section and download all applicable files", notes: "" }
  ]},
  { theme: "Offer Prep", group: 4, activities: [
    { name: "Contract - Page 1 - Buyer and Seller Names", notes: "Pull legal names from property records (COJ.net) or refer to Offer Instructions" },
    { name: "Contract - Page 1 - Property Tax ID", notes: "Pull from Tax section in MLS (or COJ.net) - fill in info in Command details section" },
    { name: "Contract - Page 1, Section 1D - Personal Property", notes: "Include any other items the buyer wants" },
    { name: "Contract - Page 1, Section 1E", notes: "Make sure to list any items being excluded per the MLS (if any)" },
    { name: "Contract - Page 1, Section 2a - EMD", notes: "Check 'to be made', input 3 days, enter amt and fill in escrow agent info per Offer Instructions" },
    { name: "Contract - Page 1, Section 2c - Financing", notes: "Balance of financing is PP - EMD (put as % so that never changes)" },
    { name: "Contract - Page 1, Section 2d - Other", notes: "Input % if buyer is getting DPA program" },
    { name: "Contract - Page 1, Section 2e - Balance to Close", notes: "Balance to close is PP - EMD - financing" },
    { name: "Contract - Page 1, Section 3a - Time for Acceptance", notes: "Input 2 days @ 11:59pm from day of offer" },
    { name: "Contract - Page 2, Section 4 - Closing", notes: "Make at least 45 days out if possible" },
    { name: "Contract - Page 2, Section 7 - Assignability", notes: "Select one radio button (usually may NOT assign)" },
    { name: "Contract - Page 2, Section 8 - Financing", notes: "Input # of days per the lender, and select loan type (Conv/FHA/VA, fixed/arm, etc)" },
    { name: "Contract - Page 3, Section 9 - Closing Costs (Seller)", notes: "If asking for seller to pay portion of CC, write 'see additional terms' in 'Other' box" },
    { name: "Contract - Page 3, Section 9 - Closing Costs (Buyer)", notes: "Add transaction fee $199 (or new brokerage fee) into 'Other' section" },
    { name: "Contract - Page 4, Section 9c - Title", notes: "Select button that seller will choose closing agent" },
    { name: "Contract - Page 4, Section 9e - Survey", notes: "Indicate whether buyer requests seller to pay for a home warranty" },
    { name: "Contract - Page 4, Section 9f - Special Assessments", notes: "Select seller will pay prior to closing and buyer will pay after" },
    { name: "Contract - Page 5, Section 12 - Inspection and Right to Cancel", notes: "Default to 15 days but to make offer strong, can be 7-10" },
    { name: "Contract - Page 11, Section 19 - Addenda", notes: "Select all applicable addenda that will accompany the offer (ie HOA (B), FHA (E), V, GG)" },
    { name: "Contract - Page 11, Section 19 - GG Addendum", notes: "Check box GG and include that addendum with all other docs for buyer signature" },
    { name: "Contract - Page 12, Section 20 - Additional Terms (Closing Costs)", notes: "Write 'Seller to contribute xx% toward buyer closing costs and prepaids'" },
    { name: "Contract - Page 12, Section 20 - Additional Terms (Compensation)", notes: "Write buyer compensation contingency clause for Buyer Broker agreement" },
    { name: "Contract - Page 13, Listing Sales Associate", notes: "Input Listing Agent and Broker name in applicable fields" },
    { name: "Prepare HRE Affiliated Business Disclosure", notes: "" },
    { name: "Prepare GG Addendum for Compensation Agreement", notes: "" },
    { name: "Prepare HOA Addendum", notes: "If property is HOA; Use HOA Addendum already signed by sellers" },
    { name: "Prepare Condo Addendum", notes: "If property is Condo; Use Addendum already signed by sellers" },
    { name: "Prepare CDD Addendum", notes: "If property located in CDD; Use Addendum already signed by sellers" },
    { name: "Prepare FHA/VA Addendum", notes: "If buyer doing FHA/VA financing; Use Addendum already signed by sellers" },
    { name: "Prepare Lead Based Paint", notes: "If property was built prior to 1978; Use Addendum already signed by sellers" },
    { name: "Prepare Flood Disclosure", notes: "Seller should provide in Documents section in MLS - if not, prepare and add to pkg" },
    { name: "Review/Request Seller Disclosure", notes: "Pull down from MLS or request from agent - include with docs for buyer to sign" },
    { name: "Send PASA and all addenda to buyer for signature", notes: "Make sure to include all applicable addenda above" },
    { name: "Submit an Offer per instructions", notes: "Add contingencies (inspection, finance)" },
    { name: "Complete Broker Compensation", notes: "Request commission structure from Listing Agent, sign and include with offer" },
    { name: "Look up other agent in MLS to see production", notes: "" },
    { name: "Pull down tax/property records from MLS", notes: "Can find under Tax Info tab on MLS --> Print page" }
  ]},
  { theme: "Under Contract", group: 5, activities: [
    { name: "Create transaction in Dot Loop", notes: "Create an opportunity and fill out all applicable info", daysOffset: 1 },
    { name: "Print/save a copy of MLS", notes: "", daysOffset: 1 },
    { name: "Send Executed Contract & Addenda to Lender", notes: "Send contract/HOA/CDD/FHAVA/GG Rider to lender", daysOffset: 1 },
    { name: "Pull all HOA from MLS or request from agent and/or Title Co", notes: "Ask for Bylaws, Rules & Regs, Decs and Covenants, Articles of Incorporation, YE Financial stmts", daysOffset: 3 },
    { name: "Pull Survey from MLS or request from agent and/or Title Co", notes: "If no survey, advise title company that one will need to be ordered (buyer cost)", daysOffset: 3 },
    { name: "Order WDO / Well Inspections", notes: "Only required if FHA/VA", daysOffset: 5 },
    { name: "Submit EMD to Title company", notes: "", daysOffset: 3 },
    { name: "Schedule Inspection through ShowingTime", notes: "Once inspection has been confirmed, schedule through ST and provide inspector with code", daysOffset: 5 },
    { name: "Inspections - Review and create amendment to contract", notes: "Send repair request along with signed amendment", daysOffset: 10 },
    { name: "Confirm Buyer Appraisal ordered", notes: "Update spreadsheet with date ordered & again when complete", daysOffset: 15 },
    { name: "Confirm Buyer has secured HOI", notes: "Email buyer the Win Mit and 4pt from the inspection for HOI quotes", daysOffset: 15 },
    { name: "Submit all required 'Under Contract' and 'Offer Prep' items to Dot Loop", notes: "Only do once inspections have been completed and repair requests finalized", daysOffset: 15 },
    { name: "Add copy of EMD to Dot Loop", notes: "", daysOffset: 5 },
    { name: "Upload Survey to Dot Loop", notes: "Download from MLS or request from Agent (if no survey, contact Title)", daysOffset: 10 },
    { name: "Confirm Lender is C2C", notes: "This needs to be done at least 1-2 weeks prior to the closing date on contract", daysOffset: 30 }
  ]},
  { theme: "Pre-close", group: 6, activities: [
    { name: "Schedule Walkthrough", notes: "Confirm with buyer and schedule final walkthrough 1-2 days prior to closing" },
    { name: "Purchase Closing Gift", notes: "" },
    { name: "Collect keys/garage door openers/alarm codes", notes: "Confirm with agent that keys/garage door openers/alarm codes will be at closing" },
    { name: "Create offer and submit DA", notes: "Ensure DA request matches compensation agreement" },
    { name: "Confirm Title company is C2C", notes: "Once appraisal and conditions are in, email title to confirm nothing outstanding" },
    { name: "Submit DA & Indicate who's paying Transaction Fee ($250)", notes: "Can combine this task when confirming Title is clear to close" },
    { name: "Receive CD from Lender and Review with Client", notes: "Personally review for E&O and make sure the client understands CTC" },
    { name: "Confirm with Buyer that title has told them how they expect funds", notes: "Title company should tell the client how to bring the money due at closing (ie wire, cashier check, etc)" },
    { name: "Email Utility PDF", notes: "Helpful so the buyers can start making appts to have services turned on" }
  ]},
  { theme: "Closed", group: 7, activities: [
    { name: "Email all docs to Client", notes: "Include contract, appraisal, title (if avail), survey, HOA (if appl)" },
    { name: "Update contact info / create Smart Plan", notes: "Include new address, sale date, and add to Homestead Exemption plan" },
    { name: "Ask for a Google Review", notes: "Provide link and ask them to please provide a review" },
    { name: "Submit Closure items to Dot Loop", notes: "Survey, DA (uploaded by MC), Executed Alta" }
  ]}
];

export default BUYER_TEMPLATE;
