const BUYER_TEMPLATE = [
  { theme: "New Lead", group: 1, activities: [
    { name: "Create new contact in CRM and add all info", notes: "Collect name, phone number, email, address" },
    { name: "Update CRM to reflect correct status", notes: "Update CRM to reflect whether New Lead or Active Lead" },
    { name: "Set up on an Automated Campaign", notes: "Make sure you select the right campaign for the status (ie New Lead, Active Lead, Prospect, etc)" },
    { name: "Add all Hashtags", notes: "Make this intuitive for future use (ie VA = military, FTHB, etc - if you use a strategic outreach cycle, add that)" },
    { name: "Use SM to collect info like children's names, birthdays, activities", notes: "This will help on your outreach to know their milestones, hobbies, etc" }
  ]},
  { theme: "Lead", group: 2, activities: [
    { name: "Prepare Buyer Presentation according to layout in 'Step by Step Guides'", notes: "Template available or use your own" },
    { name: "Send all comms BEFORE presentation according to 'Step by Step Guides'", notes: "" },
    { name: "Create transaction in Document Signing System", notes: "Create in both the electronic signing system (ie Docusign, Form Simplicity) and document management system (ie Dot Loop, broker specific)" },
    { name: "Prepare Exclusive Transaction Broker Agreement", notes: "Negotiate commission and add to section 7a along with applicable brokerage fee" },
    { name: "Review/Execute Exclusive Transaction Broker Agreement with Buyers", notes: "Must be done before any houses have been shown" },
    { name: "Create/update row in Sales spreadsheet", notes: "Template available or use your own" },
    { name: "Create transaction in CLOSd", notes: "" },
    { name: "Create folders on Computer (ie OneDrive) & Email (ie Outlook, Gmail)", notes: "Add all docs from Contract/Doc Prep sections into folder once complete" }
  ]},
  { theme: "Active Showing", group: 3, activities: [
    { name: "Establish lender", notes: "" },
    { name: "Get pre-qualification letter", notes: "" },
    { name: "Have buyers provide income/asset documentation", notes: "" },
    { name: "Create MLS subscription based on preferences", notes: "Add buyer as contact in MLS, invite to portal, set the subscription up for Daily delivery" },
    { name: "Schedule showings through ShowingTime", notes: "As properties are found, schedule showing tours in Showing Time via MLS" },
    { name: "Check Documents section and download all applicable files", notes: "" }
  ]},
  { theme: "Offer Prep", group: 4, activities: [
    { name: "Contract - Page 1 - Buyer and Seller Names", notes: "1. Pull legal names from county property records or refer to Offer Instructions" },
    { name: "Contract - Page 1 - Property Tax ID", notes: "Pull from Tax section in MLS (or county prop records)" },
    { name: "Contract - Page 1, Section 1D - Personal Property", notes: "Include any other items the buyer wants (ie removable shed, washer/dryer, etc)" },
    { name: "Contract - Page 1, Section 1E", notes: "Make sure to list any items in the above that are being excluded per the MLS (if any)" },
    { name: "Contract - Page 1, Section 2a - EMD", notes: "Check 'to be made', input 3 days, enter amt and fill in escrow agent info per Offer Instructions" },
    { name: "Contract - Page 1, Section 2c - Financing", notes: "Put as a % so it never needs to change if the price changes (ie 100%, 96.5%)" },
    { name: "Contract - Page 1, Section 2d - Other", notes: "Input % if buyer is getting DPA program" },
    { name: "Contract - Page 1, Section 2e - Balance to Close", notes: "Balance to close is PP - EMD - financing (personally I put 'Balance')" },
    { name: "Contract - Page 1, Section 3a - Time for Acceptance", notes: "Standard is 48hrs (ie so if Tues, input Thursday)" },
    { name: "Contract - Page 2, Section 4 - Closing", notes: "Negotiable and what's important to client & seller (can be 30-60 days)" },
    { name: "Contract - Page 2, Section 7 - Assignability", notes: "Select one radio button (usually may NOT assign)" },
    { name: "Contract - Page 2, Section 8 - Financing", notes: "Input # of days per the lender, and select what type of loan (Conv/FHA/VA, fixed/arm, etc)" },
    { name: "Contract - Page 3, Section 9 - Closing Costs (Seller)", notes: "If asking for seller to pay portion of CC, write 'see additional terms' in 'Other' box" },
    { name: "Contract - Page 3, Section 9 - Closing Costs (Buyer)", notes: "Add broker transaction fee into 'Other' section (can also include TC fee)" },
    { name: "Contract - Page 4, Section 9c - Title", notes: "Select button that seller will choose closing agent unless otherwise agreed" },
    { name: "Contract - Page 4, Section 9e - Survey", notes: "Indicate whether buyer requests seller to pay for a home warranty" },
    { name: "Contract - Page 4, Section 9f - Special Assessments", notes: "Discuss with buyers but typically you would want the Sellers to pay any special assessments in full" },
    { name: "Contract - Page 5, Section 12 - Inspection and Right to Cancel", notes: "Default to 15 days but to make offer strong, can be 7-10" },
    { name: "Contract - Page 11, Section 19 - Addenda", notes: "Select all applicable addenda that will accompany the offer (ie HOA (B), FHA (E), V, GG)" },
    { name: "Contract - Page 11, Section 19 - GG Addendum", notes: "Check box GG and include that addendum with all other docs for buyer signature" },
    { name: "Contract - Page 12, Section 20 - Additional Terms", notes: "Write 'Seller to contribute xx% toward buyer closing costs and prepaids' (this will vary)" },
    { name: "Contract - Page 13, Listing Sales Associate", notes: "Input Listing Agent and Broker name in applicable fields" },
    { name: "Prepare Affiliated Business Arrangement", notes: "Specific to your brokerage" },
    { name: "Prepare GG Addendum for Compensation Agreement", notes: "" },
    { name: "Prepare HOA Addendum", notes: "If property is HOA; Use HOA Addendum already signed by sellers" },
    { name: "Prepare Condo Addendum", notes: "If property is Condo; Use Addendum already signed by sellers" },
    { name: "Prepare CDD Addendum", notes: "If property located in CDD; Use Addendum already signed by sellers" },
    { name: "Prepare FHA/VA Addendum", notes: "If buyer doing FHA/VA financing; Use Addendum already signed by sellers" },
    { name: "Prepare Lead Based Paint", notes: "If property was built prior to 1978; Use Addendum already signed by sellers" },
    { name: "Prepare Flood Disclosure", notes: "Seller should provide in Documents section in MLS - if not, prepare and add to pkg" },
    { name: "Review/Request Seller Disclosure", notes: "Pull down from MLS or request from agent - include with docs for buyer to sign" },
    { name: "Send PASA and all addenda to buyer for signature", notes: "Make sure to include all applicable addenda above" },
    { name: "Submit an Offer per instructions", notes: "Add contingencies (inspection, finance)" },
    { name: "Complete Broker Compensation", notes: "Request commission structure from Listing Agent, sign and include with offer" },
    { name: "Verify Tax info via County Property appraiser", notes: "Save a copy for your records" }
  ]},
  { theme: "Under Contract", group: 5, activities: [
    { name: "Print/save a copy of MLS", notes: "", daysOffset: 1 },
    { name: "Send Executed Contract & Addenda to Lender", notes: "Send contract/HOA/CDD/FHAVA/GG Rider to lender to and advise again once have come to terms on inspection", daysOffset: 1 },
    { name: "Pull all HOA from MLS or request from agent and/or Title Co", notes: "Ask for Bylaws, Rules & Regs, Decs and Covenants, Articles of Incorporation, YE Financial stmts", daysOffset: 1 },
    { name: "Pull Survey from MLS or request from agent and/or Title Co", notes: "If no survey, advise title company that one will need to be ordered (buyer cost)", daysOffset: 1 },
    { name: "Order WDO / Well Inspections", notes: "Only required if FHA/VA", daysOffset: 2 },
    { name: "Confirm EMD submitted to Title company", notes: "", daysOffset: 3 },
    { name: "Schedule Inspection through ShowingTime", notes: "Once inspection has been confirmed, schedule through ST and provide inspector with code", daysOffset: 5 },
    { name: "Inspections - Review and create amendment to contract", notes: "Send repair request along with signed amendment", daysOffset: 10 },
    { name: "Confirm Buyer Appraisal ordered", notes: "Update spreadsheet with date ordered & again when complete", daysOffset: 15 },
    { name: "Confirm Buyer has secured HOI", notes: "Email buyer the Win Mit and 4pt from the inspection and tell them to provide these to HOI companies when getting quotes", daysOffset: 15 },
    { name: "Submit all required 'Under Contract' and 'Offer Prep' items to TM System", notes: "", daysOffset: 15 },
    { name: "Add copy of EMD to TM system", notes: "", daysOffset: 15 },
    { name: "Upload Survey to TM System", notes: "Download from MLS or request from Agent (if no survey, contact Title)", daysOffset: 15 },
    { name: "Confirm Lender is C2C", notes: "Template Available - This needs to be done at least 1-2 weeks prior to the closing date on contract" },
    { name: "Request Prelim ALTA from Title Company", notes: "Generally needed by brokerage in order to issue the DA (way you get paid as an agent)" }
  ]},
  { theme: "Pre-close", group: 6, activities: [
    { name: "Confirm all docs submitted for compliance and request DA from broker", notes: "Ensure DA request matches compensation agreement" },
    { name: "Confirm Title company is C2C", notes: "Template Available - Once appraisal and conditions are in, email title to confirm nothing outstanding" },
    { name: "Submit DA & Indicate who's paying Transaction Fee ($250)", notes: "Template Available - Can combine this task when confirming Title is clear to close" },
    { name: "Schedule Walkthrough", notes: "Confirm with buyer and schedule final walkthrough day of closing" },
    { name: "Purchase Closing Gift", notes: "" },
    { name: "Collect keys/garage door openers/alarm codes", notes: "Confirm with agent that keys/garage door openers/alarm codes will be at closing" },
    { name: "Receive CD from Lender and Review with Client", notes: "The lender does this as well but it is good practice to personally review for E&O and make sure the client understands CTC" },
    { name: "Confirm with Buyer that title has told them how they expect funds", notes: "Title company should tell the client how to bring the money due at closing (ie wire, cashier check, etc)" },
    { name: "Send Pre-closing Email & Attach Utility PDF", notes: "Template Available - Helpful so the buyers can start making appts to have services turned on" }
  ]},
  { theme: "Closed", group: 7, activities: [
    { name: "Send Closure Email & all docs to Client", notes: "Template Available - Include contract, appraisal, title (if avail), survey, HOA (if appl)" },
    { name: "Update contact info / create new Automated Campaign", notes: "Include new address, sale date, add to Homestead Campaign, proactive outreach, change status to 'Sphere' or 'Closed'" },
    { name: "Ask for a Google Review", notes: "Template Available - Provide personal link and ask them to pls provide a review" },
    { name: "Submit Closure items to Transaction Mgmt system", notes: "Survey, DA, Final Executed Alta" },
    { name: "Update sales board & spreadsheet with all info", notes: "Include other agent & TC (if appl), title co, and all known fields/deadlines" }
  ]}
];

export default BUYER_TEMPLATE;
